import type { Metadata } from "next";
import "./globals.css";
import { makeClient } from "./lib/apollo-client";
import { ApolloNextAppProvider } from "@apollo/experimental-nextjs-app-support/ssr";

export const metadata: Metadata = {
  title: "GraphQL Sample",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body>
        <ApolloNextAppProvider makeClient={makeClient}>
          {children}
        </ApolloNextAppProvider>
      </body>
    </html>
  );
}
