version: '3.8'

services:

  nextjs:
    container_name: nextjs
    build: ./frontend/
    ports:
      - "3000:3000" # Next.jsのポート
    restart: always
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - nestjs

  nestjs:
    container_name: nestjs
    build: ./backend/
    ports:
      - "8000:8000" # NestJSのポート
      - "5555:5555" # Prisma Studioのポート
    restart: always
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - ./docker/postgres/init.d:/docker-entrypoint-initdb.d
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      POSTGRES_DB: postgres
    hostname: postgres
    restart: always
    user: root

volumes:
  postgres-data:
    driver: local